### ISSUE TITLE
Accessing S3 with custom InstanceProfile does not work

### ISSUE THREAD

**Issue by zobo** [awsdocs/aws-elastic-beanstalk-developer-guide#139]
I'm not sure if this is a documentation problem or a technical bug or just me not understanding things. I'll try to break down things as much as I can.

Fist, this is the page I am referring to: https://github.com/awsdocs/aws-elastic-beanstalk-developer-guide/blob/main/doc_source/https-storingprivatekeys.md

```
Resources:
  AWSEBAutoScalingGroup:
    Metadata:
      AWS::CloudFormation::Authentication:
        S3Auth:
          type: "s3"
          buckets: ["elasticbeanstalk-us-west-2-123456789012"]
          roleName: 
            "Fn::GetOptionSetting": 
              Namespace: "aws:autoscaling:launchconfiguration"
              OptionName: "IamInstanceProfile"
              DefaultValue: "aws-elasticbeanstalk-ec2-role"
files:
  # Private key
  "/etc/pki/tls/certs/server.key":
    mode: "000400"
    owner: root
    group: root
    authentication: "S3Auth"
    source: https://elasticbeanstalk-us-west-2-123456789012.s3.us-west-2.amazonaws.com/server.key
```

It says: download this file from S3 and use `S3Auth` for authentication. The **role** in use is either the default "aws-elasticbeanstalk-ec2-**role**" or whatever is defined in the "IamInstance**Profile**". Notice the strange difference.

We have a bunch of CloudFormation templates we use to spin up dev and prod environments and in one, where I tried to use this sort of approach, we use a custom Profile.

```
  MYConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ...
      OptionSettings:
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: IamInstanceProfile
        Value:  !Ref MYInstanceProfile 
        ...

  MYInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Roles:
        - !Ref MYInstanceRole 

  MYInstanceRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
       Version: 2012-10-17
       Statement:
          - Effect: Allow
            Principal:
               Service:
                - ec2.amazonaws.com
            Action:
             - sts:AssumeRole
      Description: Beanstalk EC2 role
      ManagedPolicyArns: 
       - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier
       - arn:aws:iam::aws:policy/AWSElasticBeanstalkMulticontainerDocker
       - arn:aws:iam::aws:policy/AWSElasticBeanstalkWorkerTier 
```
As seen in https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-autoscaling-launchconfiguration.html the `IamInstanceProfile` takes a Profile, not a Role.

Everything works, except the downloading of the file from S3. In the logs I could see an error like this `404 Client Error: Not Found`.

I dove deep into the beanstalk python code to actually figure out where the error comes from.

When the python code tried to download the requested S3 file it first fetches the security credentials. This is done over a HTTP connection to some internal address:
`http://169.254.169.254/latest/meta-data/iam/security-credentials/MY-elastic-beanstalk-MYInstanceProfile-xxxxxxxxxxxxx`

The HTTP response here was the `HTTP/1.0 404 Not Found`.

Researching this internal HTTP server I figured it contains the **role** ARN, not the **profile** ARN:

```
[root@ip-xxx-xxx-xxx-xxx ~]# curl http://169.254.169.254/latest/meta-data/iam/security-credentials ; echo 

MY-elastic-beanstalk-MYInstanceRole-yyyyyyyyyyyyy

[root@ip-xxx-xxx-xxx-xxx ~]# curl http://169.254.169.254/latest/meta-data/iam/security-credentials/MY-elastic-beanstalk-MYInstanceRole-yyyyyyyyyyyyy ; echo 

{
  "Code" : "Success",
  "LastUpdated" : "...",
  "Type" : "AWS-HMAC",
  "AccessKeyId" : "...",
  "SecretAccessKey" : "...",
  "Token" : "...",
  "Expiration" : "..."
}
```

If I hardcode the role ARN (MYInstanceRole-yyyyyyyyyyyyy) in the `roleName` the script can download the file, if I follow the documentation and let it evaluate `IamInstanceProfile` it does not work. I could not find a way to evaluate the Role, or if I could, some dependency loop caused everything to break down...

Is this a documentation flaw, design flaw, or just me missing something.

Thanks!
