### ISSUE TITLE
customize-containers-windows-ec2.md: document order of processing for packages

### ISSUE THREAD

**Issue by ajoga** [awsdocs/aws-elastic-beanstalk-developer-guide#34]
Hello, 

I'm having troubles, and I find the documentation lacking regarding how to install multiple MSI packages, and also how to explicit the order of their installation. As keys should not be duplicated, I guess those example are wrong : 

```
packages:
  msi:
    mysql: https://dev.mysql.com/get/Downloads/Connector-Net/mysql-connector-net-8.0.11.msi
packages:
  msi:
    otherpackage: https://example.tld/test.msi
```

```
packages:
  msi:
    mysql: https://dev.mysql.com/get/Downloads/Connector-Net/mysql-connector-net-8.0.11.msi
  msi:
    otherpackage: https://example.tld/test.msi
```

```
packages:
  msi:
    mysql: https://dev.mysql.com/get/Downloads/Connector-Net/mysql-connector-net-8.0.11.msi
  msi2:
    otherpackage: https://example.tld/test.msi
```

But I were not able to make work this snippet, it seemed that only the latter entry was processed :

```
packages:
  msi:
    mysql: https://dev.mysql.com/get/Downloads/Connector-Net/mysql-connector-net-8.0.11.msi
    otherpackage: https://example.tld/test.msi
```

I suggest that the proper way to do should at least be shown as an example, as it's been done for `files:`

Thank you for your time
