### ISSUE TITLE
AWS::CFN::Authentication examples issue with custom IamInstanceProfile

### ISSUE THREAD

**Issue by taraslayshchuk** [awsdocs/aws-elastic-beanstalk-developer-guide#58]
Examples with [`AWS::CloudFormation::Authentication`](https://github.com/awsdocs/aws-elastic-beanstalk-developer-guide/search?q=AWS%3A%3ACloudFormation%3A%3AAuthentication&unscoped_q=AWS%3A%3ACloudFormation%3A%3AAuthentication) have issue in case of using a custom IAM profile, as AWS CFN Authentication [rolename parameter](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-authentication.html#cfn-cloudformation-authentication-rolename) is accepting only a role name, not a profile name.

**Comment by emreisikligil** [comment]
I can get it worked with the following change
```
          roleName: 
            "Fn::GetOptionSetting": 
              Namespace: "aws:elasticbeanstalk:environment"
              OptionName: "ServiceRole"
              DefaultValue: "YourDefaultServiceRole"
```
